# Generated by Django 2.1.7 on 2019-03-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_mmr', models.IntegerField()),
                ('current_rank', models.IntegerField()),
                ('NA_mmr', models.IntegerField(null=True)),
                ('NA_rank', models.IntegerField(null=True)),
                ('EU_mmr', models.IntegerField(null=True)),
                ('EU_rank', models.IntegerField(null=True)),
                ('AS_mmr', models.IntegerField(null=True)),
                ('AS_rank', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_queried', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_queried',
            field=models.DateTimeField(null=True),
        ),
    ]
