# Generated by Django 2.1.7 on 2019-03-14 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190314_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermeta',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Player'),
        ),
    ]
