# Generated by Django 2.1.7 on 2019-03-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_playermeta_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermeta',
            name='current_mmr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playermeta',
            name='current_rank',
            field=models.IntegerField(null=True),
        ),
    ]
