# Generated by Django 2.1.7 on 2019-03-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190314_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='image',
        ),
        migrations.AddField(
            model_name='player',
            name='current_mmr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='current_rank',
            field=models.IntegerField(null=True),
        ),
    ]
