# Generated by Django 2.1.7 on 2019-03-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190314_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_level',
            field=models.IntegerField(null=True),
        ),
    ]
