# Generated by Django 2.1.7 on 2019-03-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_report_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermeta',
            name='last_queried',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='region',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('NA', 'America'), ('EU', 'Europe'), ('AS', 'Asia')], default='GLOBAL', max_length=10),
        ),
    ]
