# Generated by Django 2.1.7 on 2019-03-15 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190315_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerQuery',
        ),
        migrations.AddField(
            model_name='report',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
