# Generated by Django 2.1.7 on 2019-03-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='image',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='operator',
            name='logo',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
