# Generated by Django 2.1.7 on 2019-03-23 03:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=255)),
                ('p_user', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('current_level', models.IntegerField(null=True)),
                ('current_mmr', models.IntegerField(null=True)),
                ('current_rank', models.IntegerField(null=True)),
                ('last_queried', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_mmr', models.IntegerField(null=True)),
                ('current_rank', models.IntegerField(null=True)),
                ('NA_mmr', models.IntegerField(null=True)),
                ('NA_rank', models.IntegerField(null=True)),
                ('EU_mmr', models.IntegerField(null=True)),
                ('EU_rank', models.IntegerField(null=True)),
                ('AS_mmr', models.IntegerField(null=True)),
                ('AS_rank', models.IntegerField(null=True)),
                ('last_queried', models.DateTimeField(null=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_ip', models.GenericIPAddressField()),
                ('region', models.CharField(choices=[('GLOBAL', 'Global'), ('NA', 'America'), ('EU', 'Europe'), ('AS', 'Asia')], default='GLOBAL', max_length=10)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.Operator')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
        ),
    ]
