# Generated by Django 2.1.7 on 2019-03-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='current_level',
        ),
        migrations.RemoveField(
            model_name='player',
            name='current_mmr',
        ),
        migrations.RemoveField(
            model_name='player',
            name='current_rank',
        ),
        migrations.AddField(
            model_name='playermeta',
            name='current_level',
            field=models.IntegerField(null=True),
        ),
    ]
